@extends('layouts.app')

@section('title', 'Print Credit Note')

@section('content')
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="mb-0">Credit Note #{{ $creditNote->cn_no }}</h4>
                        <button class="btn btn-primary" onclick="window.print()"><i class="mdi mdi-printer"></i> Print</button>
                    </div>
                    <hr>
                    <dl class="row mb-0">
                        <dt class="col-sm-4">Status</dt>
                        <dd class="col-sm-8">{{ $creditNote->status }}</dd>
                        <dt class="col-sm-4">Original Invoice</dt>
                        <dd class="col-sm-8">{{ $creditNote->original_invoice_no }}</dd>
                        <dt class="col-sm-4">Buyer</dt>
                        <dd class="col-sm-8">{{ $creditNote->buyer_name }}</dd>
                        <dt class="col-sm-4">Reason</dt>
                        <dd class="col-sm-8">{{ $creditNote->reason }}</dd>
                        <dt class="col-sm-4">Reason Code</dt>
                        <dd class="col-sm-8">{{ $creditNote->reason_code }}</dd>
                        <dt class="col-sm-4">Amount</dt>
                        <dd class="col-sm-8">{{ number_format($creditNote->total_amount, 2) }} {{ $creditNote->currency }}</dd>
                        <dt class="col-sm-4">Created</dt>
                        <dd class="col-sm-8">{{ $creditNote->created_at->format('M d, Y H:i') }}</dd>
                    </dl>
                    <hr>
                    <h5>Items</h5>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Item</th>
                                    <th>Qty</th>
                                    <th>Unit Price</th>
                                    <th>Total</th>
                                    <th>Tax</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($creditNote->items as $item)
                                <tr>
                                    <td>{{ $item->item_name }}</td>
                                    <td>{{ $item->quantity }}</td>
                                    <td>{{ number_format($item->unit_price, 2) }}</td>
                                    <td>{{ number_format($item->total_amount, 2) }}</td>
                                    <td>{{ number_format($item->tax_amount, 2) }}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-4 text-center">
                        <small>Generated by EFRIS Invoice Management System</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 